In [50]:
import requests,json

api_key="32b45e398e410de74bbb7bc204946c57"

city=input("Enter City:")
url="http://api.openweathermap.org/geo/1.0/direct?q="+city+"&appid="+api_key
response=requests.get(url)
result=response.json()
print(json.dumps(result,indent=3))

Enter City: Ahmedabad

[
   {
      "name": "Ahmedabad",
      "local_names": {
         "uk": "\u0410\u0445\u043c\u0435\u0434\u0430\u0431\u0430\u0434",
         "mr": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
         "pl": "Ahmadabad",
         "hi": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
         "de": "Ahmedabad",
         "ne": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
         "ta": "\u0b85\u0b95\u0bae\u0ba4\u0bbe\u0baa\u0bbe\u0ba4\u0bcd",
         "tt": "\u04d8\u0445\u043c\u04d9\u0442\u0430\u0431\u0430\u0434",
         "cs": "Ahmad\u00e1b\u00e1d",
         "en": "Ahmedabad",
         "ml": "\u0d05\u0d39\u0d2e\u0d4d\u0d2e\u0d26\u0d3e\u0d2c\u0d3e\u0d26\u0d4d",
         "oc": "Ahmadabad",
         "te": "\u0c05\u0c39\u0c4d\u0c2e\u0c26\u0c3e\u0c2c\u0c3e\u0c26\u0c4d",
         "ja": "\u30a2\u30d5\u30de\u30c0\u30fc\u30d0\u30fc\u30c9",
         "ru": "\u0410\u0445\u043c\u0430\u0434\u0430\u0431\u0430\u0434",
         "pa": "\u0a05\u0a39\u0a3f\u0a2e\u0a26\u0a3e\u0a2c\u0a3e\u0a26",
         "zh": "\u827e\u54c8\u8fc8\u8fbe\u5df4\u5fb7",
         "feature_name": "Ahmedabad",
         "ar": "\u0623\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
         "gu": "\u0a85\u0aae\u0aa6\u0abe\u0ab5\u0abe\u0aa6",
         "he": "\u05d0\u05d7\u05de\u05d3\u05d0\u05d1\u05d0\u05d3",
         "kn": "\u0c85\u0cb9\u0ccd\u0cae\u0ca6\u0cbe\u0cac\u0cbe\u0ca6\u0ccd",
         "bn": "\u0986\u09b9\u09ae\u09c7\u09a6\u09be\u09ac\u09be\u09a6",
         "ur": "\u0627\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
         "or": "\u0b05\u0b39\u0b2e\u0b26\u0b3e\u0b2c\u0b3e\u0b26",
         "ascii": "Ahmedabad",
         "eo": "Ahmadabado"
      },
      "lat": 23.0215374,
      "lon": 72.5800568,
      "country": "IN",
      "state": "Gujarat"
   }
]

In [51]:
lat=result[0]["lat"]
print(lat)

23.0215374

In [52]:
lon=result[0]["lon"]
print(lon)

72.5800568

In [53]:

api_key="32b45e398e410de74bbb7bc204946c57"
url2=f"http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid={api_key}"
response=requests.get(url2)
result=response.json()
print(json.dumps(result,indent=3))

{
   "coord": {
      "lon": 72.5801,
      "lat": 23.0215
   },
   "list": [
      {
         "main": {
            "aqi": 1
         },
         "components": {
            "co": 85.04,
            "no": 0.31,
            "no2": 1.23,
            "o3": 42.95,
            "so2": 1.19,
            "pm2_5": 3.96,
            "pm10": 11.79,
            "nh3": 4.8
         },
         "dt": 1781583882
      }
   ]
}

In [54]:
aqi=result["list"][0]["main"]["aqi"]
print("aqi : ",aqi)

aqi :  1

In [61]:
api_key="32b45e398e410de74bbb7bc204946c57"
url3=f"http://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={api_key}"
response=requests.get(url3)
result=response.json()
print(json.dumps(result,indent=3))

{
   "cod": "200",
   "message": 0,
   "cnt": 40,
   "list": [
      {
         "dt": 1781589600,
         "main": {
            "temp": 309.76,
            "feels_like": 311.45,
            "temp_min": 309.76,
            "temp_max": 309.76,
            "pressure": 1007,
            "sea_level": 1007,
            "grnd_level": 1002,
            "humidity": 34,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
            }
         ],
         "clouds": {
            "all": 3
         },
         "wind": {
            "speed": 4.31,
            "deg": 230,
            "gust": 4.74
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "d"
         },
         "dt_txt": "2026-06-16 06:00:00"
      },
      {
         "dt": 1781600400,
         "main": {
            "temp": 310.87,
            "feels_like": 312.44,
            "temp_min": 310.87,
            "temp_max": 313.08,
            "pressure": 1006,
            "sea_level": 1006,
            "grnd_level": 999,
            "humidity": 31,
            "temp_kf": -2.21
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
            }
         ],
         "clouds": {
            "all": 2
         },
         "wind": {
            "speed": 5.09,
            "deg": 244,
            "gust": 5.39
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "d"
         },
         "dt_txt": "2026-06-16 09:00:00"
      },
      {
         "dt": 1781611200,
         "main": {
            "temp": 312.27,
            "feels_like": 313.85,
            "temp_min": 312.27,
            "temp_max": 313.52,
            "pressure": 1004,
            "sea_level": 1004,
            "grnd_level": 997,
            "humidity": 28,
            "temp_kf": -1.25
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
            }
         ],
         "clouds": {
            "all": 1
         },
         "wind": {
            "speed": 5.6,
            "deg": 265,
            "gust": 6.18
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "d"
         },
         "dt_txt": "2026-06-16 12:00:00"
      },
      {
         "dt": 1781622000,
         "main": {
            "temp": 308.13,
            "feels_like": 310.95,
            "temp_min": 308.13,
            "temp_max": 308.13,
            "pressure": 1005,
            "sea_level": 1005,
            "grnd_level": 1000,
            "humidity": 42,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 802,
               "main": "Clouds",
               "description": "scattered clouds",
               "icon": "03n"
            }
         ],
         "clouds": {
            "all": 31
         },
         "wind": {
            "speed": 3.58,
            "deg": 251,
            "gust": 6.14
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "n"
         },
         "dt_txt": "2026-06-16 15:00:00"
      },
      {
         "dt": 1781632800,
         "main": {
            "temp": 305.1,
            "feels_like": 307.91,
            "temp_min": 305.1,
            "temp_max": 305.1,
            "pressure": 1007,
            "sea_level": 1007,
            "grnd_level": 1001,
            "humidity": 52,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 802,
               "main": "Clouds",
               "description": "scattered clouds",
               "icon": "03n"
            }
         ],
         "clouds": {
            "all": 44
         },
         "wind": {
            "speed": 6.45,
            "deg": 279,
            "gust": 9
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "n"
         },
         "dt_txt": "2026-06-16 18:00:00"
      },
      {
         "dt": 1781643600,
         "main": {
            "temp": 304.58,
            "feels_like": 306.94,
            "temp_min": 304.58,
            "temp_max": 304.58,
            "pressure": 1006,
            "sea_level": 1006,
            "grnd_level": 1001,
            "humidity": 52,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01n"
            }
         ],
         "clouds": {
            "all": 0
         },
         "wind": {
            "speed": 4.92,
            "deg": 265,
            "gust": 6.49
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "n"
         },
         "dt_txt": "2026-06-16 21:00:00"
      },
      {
         "dt": 1781654400,
         "main": {
            "temp": 303.38,
            "feels_like": 305.62,
            "temp_min": 303.38,
            "temp_max": 303.38,
            "pressure": 1006,
            "sea_level": 1006,
            "grnd_level": 1001,
            "humidity": 56,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01n"
            }
         ],
         "clouds": {
            "all": 0
         },
         "wind": {
            "speed": 4.24,
            "deg": 248,
            "gust": 5.89
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "n"
         },
         "dt_txt": "2026-06-17 00:00:00"
      },
      {
         "dt": 1781665200,
         "main": {
            "temp": 305.06,
            "feels_like": 307.12,
            "temp_min": 305.06,
            "temp_max": 305.06,
            "pressure": 1008,
            "sea_level": 1008,
            "grnd_level": 1003,
            "humidity": 49,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
            }
         ],
         "clouds": {
            "all": 0
         },
         "wind": {
            "speed": 5.51,
            "deg": 228,
            "gust": 6.7
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "d"
         },
         "dt_txt": "2026-06-17 03:00:00"
      },
      {
         "dt": 1781676000,
         "main": {
            "temp": 309.47,
            "feels_like": 310.94,
            "temp_min": 309.47,
            "temp_max": 309.47,
            "pressure": 1007,
            "sea_level": 1007,
            "grnd_level": 1002,
            "humidity": 34,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
            }
         ],
         "clouds": {
            "all": 0
         },
         "wind": {
            "speed": 5.94,
            "deg": 237,
            "gust": 6.94
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "d"
         },
         "dt_txt": "2026-06-17 06:00:00"
      },
      {
         "dt": 1781686800,
         "main": {
            "temp": 313,
            "feels_like": 313.98,
            "temp_min": 313,
            "temp_max": 313,
            "pressure": 1004,
            "sea_level": 1004,
            "grnd_level": 999,
            "humidity": 25,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
            }
         ],
         "clouds": {
            "all": 0
         },
         "wind": {
            "speed": 6.02,
            "deg": 241,
            "gust": 6.68
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "d"
         },
         "dt_txt": "2026-06-17 09:00:00"
      },
      {
         "dt": 1781697600,
         "main": {
            "temp": 312.61,
            "feels_like": 314.07,
            "temp_min": 312.61,
            "temp_max": 312.61,
            "pressure": 1002,
            "sea_level": 1002,
            "grnd_level": 997,
            "humidity": 27,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
            }
         ],
         "clouds": {
            "all": 0
         },
         "wind": {
            "speed": 7.28,
            "deg": 223,
            "gust": 8.25
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "d"
         },
         "dt_txt": "2026-06-17 12:00:00"
      },
      {
         "dt": 1781708400,
         "main": {
            "temp": 307.72,
            "feels_like": 310.77,
            "temp_min": 307.72,
            "temp_max": 307.72,
            "pressure": 1005,
            "sea_level": 1005,
            "grnd_level": 1000,
            "humidity": 44,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 803,
               "main": "Clouds",
               "description": "broken clouds",
               "icon": "04n"
            }
         ],
         "clouds": {
            "all": 57
         },
         "wind": {
            "speed": 3.69,
            "deg": 288,
            "gust": 5.08
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "n"
         },
         "dt_txt": "2026-06-17 15:00:00"
      },
      {
         "dt": 1781719200,
         "main": {
            "temp": 304.36,
            "feels_like": 307.69,
            "temp_min": 304.36,
            "temp_max": 304.36,
            "pressure": 1007,
            "sea_level": 1007,
            "grnd_level": 1001,
            "humidity": 57,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 803,
               "main": "Clouds",
               "description": "broken clouds",
               "icon": "04n"
            }
         ],
         "clouds": {
            "all": 64
         },
         "wind": {
            "speed": 5.64,
            "deg": 285,
            "gust": 8.21
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "n"
         },
         "dt_txt": "2026-06-17 18:00:00"
      },
      {
         "dt": 1781730000,
         "main": {
            "temp": 304.34,
            "feels_like": 306.29,
            "temp_min": 304.34,
            "temp_max": 304.34,
            "pressure": 1006,
            "sea_level": 1006,
            "grnd_level": 1001,
            "humidity": 51,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01n"
            }
         ],
         "clouds": {
            "all": 9
         },
         "wind": {
            "speed": 4.61,
            "deg": 241,
            "gust": 6.56
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "n"
         },
         "dt_txt": "2026-06-17 21:00:00"
      },
      {
         "dt": 1781740800,
         "main": {
            "temp": 303.01,
            "feels_like": 305.16,
            "temp_min": 303.01,
            "temp_max": 303.01,
            "pressure": 1007,
            "sea_level": 1007,
            "grnd_level": 1001,
            "humidity": 57,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 801,
               "main": "Clouds",
               "description": "few clouds",
               "icon": "02n"
            }
         ],
         "clouds": {
            "all": 11
         },
         "wind": {
            "speed": 5.74,
            "deg": 229,
            "gust": 7.42
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "n"
         },
         "dt_txt": "2026-06-18 00:00:00"
      },
      {
         "dt": 1781751600,
         "main": {
            "temp": 304.43,
            "feels_like": 306.67,
            "temp_min": 304.43,
            "temp_max": 304.43,
            "pressure": 1008,
            "sea_level": 1008,
            "grnd_level": 1003,
            "humidity": 52,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
            }
         ],
         "clouds": {
            "all": 4
         },
         "wind": {
            "speed": 6.17,
            "deg": 239,
            "gust": 7.5
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "d"
         },
         "dt_txt": "2026-06-18 03:00:00"
      },
      {
         "dt": 1781762400,
         "main": {
            "temp": 309.22,
            "feels_like": 310.5,
            "temp_min": 309.22,
            "temp_max": 309.22,
            "pressure": 1007,
            "sea_level": 1007,
            "grnd_level": 1001,
            "humidity": 34,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 801,
               "main": "Clouds",
               "description": "few clouds",
               "icon": "02d"
            }
         ],
         "clouds": {
            "all": 11
         },
         "wind": {
            "speed": 6.39,
            "deg": 230,
            "gust": 7.67
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "d"
         },
         "dt_txt": "2026-06-18 06:00:00"
      },
      {
         "dt": 1781773200,
         "main": {
            "temp": 311.59,
            "feels_like": 312.68,
            "temp_min": 311.59,
            "temp_max": 311.59,
            "pressure": 1004,
            "sea_level": 1004,
            "grnd_level": 998,
            "humidity": 28,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
            }
         ],
         "clouds": {
            "all": 0
         },
         "wind": {
            "speed": 7.48,
            "deg": 242,
            "gust": 7.77
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "d"
         },
         "dt_txt": "2026-06-18 09:00:00"
      },
      {
         "dt": 1781784000,
         "main": {
            "temp": 312.35,
            "feels_like": 312.92,
            "temp_min": 312.35,
            "temp_max": 312.35,
            "pressure": 1002,
            "sea_level": 1002,
            "grnd_level": 997,
            "humidity": 25,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
            }
         ],
         "clouds": {
            "all": 0
         },
         "wind": {
            "speed": 5.15,
            "deg": 220,
            "gust": 7.32
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "d"
         },
         "dt_txt": "2026-06-18 12:00:00"
      },
      {
         "dt": 1781794800,
         "main": {
            "temp": 307.13,
            "feels_like": 309.92,
            "temp_min": 307.13,
            "temp_max": 307.13,
            "pressure": 1005,
            "sea_level": 1005,
            "grnd_level": 999,
            "humidity": 45,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 803,
               "main": "Clouds",
               "description": "broken clouds",
               "icon": "04n"
            }
         ],
         "clouds": {
            "all": 64
         },
         "wind": {
            "speed": 3.85,
            "deg": 204,
            "gust": 4.92
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "n"
         },
         "dt_txt": "2026-06-18 15:00:00"
      },
      {
         "dt": 1781805600,
         "main": {
            "temp": 304.93,
            "feels_like": 307.35,
            "temp_min": 304.93,
            "temp_max": 304.93,
            "pressure": 1005,
            "sea_level": 1005,
            "grnd_level": 1000,
            "humidity": 51,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 803,
               "main": "Clouds",
               "description": "broken clouds",
               "icon": "04n"
            }
         ],
         "clouds": {
            "all": 73
         },
         "wind": {
            "speed": 5.7,
            "deg": 282,
            "gust": 8.01
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "n"
         },
         "dt_txt": "2026-06-18 18:00:00"
      },
      {
         "dt": 1781816400,
         "main": {
            "temp": 303.93,
            "feels_like": 305.99,
            "temp_min": 303.93,
            "temp_max": 303.93,
            "pressure": 1005,
            "sea_level": 1005,
            "grnd_level": 999,
            "humidity": 53,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 801,
               "main": "Clouds",
               "description": "few clouds",
               "icon": "02n"
            }
         ],
         "clouds": {
            "all": 13
         },
         "wind": {
            "speed": 5.68,
            "deg": 234,
            "gust": 7.66
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "n"
         },
         "dt_txt": "2026-06-18 21:00:00"
      },
      {
         "dt": 1781827200,
         "main": {
            "temp": 302.4,
            "feels_like": 304.45,
            "temp_min": 302.4,
            "temp_max": 302.4,
            "pressure": 1005,
            "sea_level": 1005,
            "grnd_level": 1000,
            "humidity": 59,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01n"
            }
         ],
         "clouds": {
            "all": 7
         },
         "wind": {
            "speed": 5.32,
            "deg": 228,
            "gust": 8.28
         },
         "visibility": 10000,
         "pop": 0,
         "sys": {
            "pod": "n"
         },
         "dt_txt": "2026-06-19 00:00:00"
      },
      {
         "dt": 1781838000,
         "main": {
            "temp": 304.46,
            "feels_like": 306.08,
            "temp_min": 304.46,
            "temp_max": 304.46,
            "pressure": 1007,
            "sea_level": 1007,
            "grnd_level": 1001,
            "humidity": 49,
            "temp_kf": 0
         },
         "weather": [
            {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
            }

In [63]:
list=result["list"]
print(list)

[{'dt': 1781589600, 'main': {'temp': 309.76, 'feels_like': 311.45, 'temp_min': 309.76, 'temp_max': 309.76, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 34, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 3}, 'wind': {'speed': 4.31, 'deg': 230, 'gust': 4.74}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-16 06:00:00'}, {'dt': 1781600400, 'main': {'temp': 310.87, 'feels_like': 312.44, 'temp_min': 310.87, 'temp_max': 313.08, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 999, 'humidity': 31, 'temp_kf': -2.21}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 2}, 'wind': {'speed': 5.09, 'deg': 244, 'gust': 5.39}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-16 09:00:00'}, {'dt': 1781611200, 'main': {'temp': 312.27, 'feels_like': 313.85, 'temp_min': 312.27, 'temp_max': 313.52, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 997, 'humidity': 28, 'temp_kf': -1.25}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 1}, 'wind': {'speed': 5.6, 'deg': 265, 'gust': 6.18}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-16 12:00:00'}, {'dt': 1781622000, 'main': {'temp': 308.13, 'feels_like': 310.95, 'temp_min': 308.13, 'temp_max': 308.13, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 42, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 31}, 'wind': {'speed': 3.58, 'deg': 251, 'gust': 6.14}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-16 15:00:00'}, {'dt': 1781632800, 'main': {'temp': 305.1, 'feels_like': 307.91, 'temp_min': 305.1, 'temp_max': 305.1, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1001, 'humidity': 52, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 44}, 'wind': {'speed': 6.45, 'deg': 279, 'gust': 9}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-16 18:00:00'}, {'dt': 1781643600, 'main': {'temp': 304.58, 'feels_like': 306.94, 'temp_min': 304.58, 'temp_max': 304.58, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 52, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 4.92, 'deg': 265, 'gust': 6.49}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-16 21:00:00'}, {'dt': 1781654400, 'main': {'temp': 303.38, 'feels_like': 305.62, 'temp_min': 303.38, 'temp_max': 303.38, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 4.24, 'deg': 248, 'gust': 5.89}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-17 00:00:00'}, {'dt': 1781665200, 'main': {'temp': 305.06, 'feels_like': 307.12, 'temp_min': 305.06, 'temp_max': 305.06, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1003, 'humidity': 49, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.51, 'deg': 228, 'gust': 6.7}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-17 03:00:00'}, {'dt': 1781676000, 'main': {'temp': 309.47, 'feels_like': 310.94, 'temp_min': 309.47, 'temp_max': 309.47, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 34, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.94, 'deg': 237, 'gust': 6.94}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-17 06:00:00'}, {'dt': 1781686800, 'main': {'temp': 313, 'feels_like': 313.98, 'temp_min': 313, 'temp_max': 313, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 999, 'humidity': 25, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 6.02, 'deg': 241, 'gust': 6.68}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-17 09:00:00'}, {'dt': 1781697600, 'main': {'temp': 312.61, 'feels_like': 314.07, 'temp_min': 312.61, 'temp_max': 312.61, 'pressure': 1002, 'sea_level': 1002, 'grnd_level': 997, 'humidity': 27, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 7.28, 'deg': 223, 'gust': 8.25}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-17 12:00:00'}, {'dt': 1781708400, 'main': {'temp': 307.72, 'feels_like': 310.77, 'temp_min': 307.72, 'temp_max': 307.72, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 44, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 57}, 'wind': {'speed': 3.69, 'deg': 288, 'gust': 5.08}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-17 15:00:00'}, {'dt': 1781719200, 'main': {'temp': 304.36, 'feels_like': 307.69, 'temp_min': 304.36, 'temp_max': 304.36, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1001, 'humidity': 57, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 64}, 'wind': {'speed': 5.64, 'deg': 285, 'gust': 8.21}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-17 18:00:00'}, {'dt': 1781730000, 'main': {'temp': 304.34, 'feels_like': 306.29, 'temp_min': 304.34, 'temp_max': 304.34, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 9}, 'wind': {'speed': 4.61, 'deg': 241, 'gust': 6.56}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-17 21:00:00'}, {'dt': 1781740800, 'main': {'temp': 303.01, 'feels_like': 305.16, 'temp_min': 303.01, 'temp_max': 303.01, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1001, 'humidity': 57, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 11}, 'wind': {'speed': 5.74, 'deg': 229, 'gust': 7.42}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-18 00:00:00'}, {'dt': 1781751600, 'main': {'temp': 304.43, 'feels_like': 306.67, 'temp_min': 304.43, 'temp_max': 304.43, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1003, 'humidity': 52, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 4}, 'wind': {'speed': 6.17, 'deg': 239, 'gust': 7.5}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-18 03:00:00'}, {'dt': 1781762400, 'main': {'temp': 309.22, 'feels_like': 310.5, 'temp_min': 309.22, 'temp_max': 309.22, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1001, 'humidity': 34, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 11}, 'wind': {'speed': 6.39, 'deg': 230, 'gust': 7.67}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-18 06:00:00'}, {'dt': 1781773200, 'main': {'temp': 311.59, 'feels_like': 312.68, 'temp_min': 311.59, 'temp_max': 311.59, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 998, 'humidity': 28, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 7.48, 'deg': 242, 'gust': 7.77}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-18 09:00:00'}, {'dt': 1781784000, 'main': {'temp': 312.35, 'feels_like': 312.92, 'temp_min': 312.35, 'temp_max': 312.35, 'pressure': 1002, 'sea_level': 1002, 'grnd_level': 997, 'humidity': 25, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.15, 'deg': 220, 'gust': 7.32}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-18 12:00:00'}, {'dt': 1781794800, 'main': {'temp': 307.13, 'feels_like': 309.92, 'temp_min': 307.13, 'temp_max': 307.13, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 999, 'humidity': 45, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 64}, 'wind': {'speed': 3.85, 'deg': 204, 'gust': 4.92}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-18 15:00:00'}, {'dt': 1781805600, 'main': {'temp': 304.93, 'feels_like': 307.35, 'temp_min': 304.93, 'temp_max': 304.93, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 73}, 'wind': {'speed': 5.7, 'deg': 282, 'gust': 8.01}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-18 18:00:00'}, {'dt': 1781816400, 'main': {'temp': 303.93, 'feels_like': 305.99, 'temp_min': 303.93, 'temp_max': 303.93, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 999, 'humidity': 53, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 13}, 'wind': {'speed': 5.68, 'deg': 234, 'gust': 7.66}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-18 21:00:00'}, {'dt': 1781827200, 'main': {'temp': 302.4, 'feels_like': 304.45, 'temp_min': 302.4, 'temp_max': 302.4, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 59, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 7}, 'wind': {'speed': 5.32, 'deg': 228, 'gust': 8.28}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-19 00:00:00'}, {'dt': 1781838000, 'main': {'temp': 304.46, 'feels_like': 306.08, 'temp_min': 304.46, 'temp_max': 304.46, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1001, 'humidity': 49, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.78, 'deg': 241, 'gust': 7.48}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-19 03:00:00'}, {'dt': 1781848800, 'main': {'temp': 309.36, 'feels_like': 310.17, 'temp_min': 309.36, 'temp_max': 309.36, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1000, 'humidity': 32, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 4}, 'wind': {'speed': 6.21, 'deg': 227, 'gust': 7.73}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-19 06:00:00'}, {'dt': 1781859600, 'main': {'temp': 312.9, 'feels_like': 313.12, 'temp_min': 312.9, 'temp_max': 312.9, 'pressure': 1003, 'sea_level': 1003, 'grnd_level': 998, 'humidity': 23, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 6.15, 'deg': 229, 'gust': 7.3}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-19 09:00:00'}, {'dt': 1781870400, 'main': {'temp': 311.74, 'feels_like': 314.02, 'temp_min': 311.74, 'temp_max': 311.74, 'pressure': 1002, 'sea_level': 1002, 'grnd_level': 997, 'humidity': 31, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 2}, 'wind': {'speed': 8.82, 'deg': 188, 'gust': 8.35}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-19 12:00:00'}, {'dt': 1781881200, 'main': {'temp': 305.98, 'feels_like': 310.27, 'temp_min': 305.98, 'temp_max': 305.98, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 999, 'humidity': 54, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 45}, 'wind': {'speed': 6.74, 'deg': 172, 'gust': 10.8}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-19 15:00:00'}, {'dt': 1781892000, 'main': {'temp': 305.76, 'feels_like': 308.14, 'temp_min': 305.76, 'temp_max': 305.76, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1000, 'humidity': 48, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 64}, 'wind': {'speed': 5.84, 'deg': 276, 'gust': 7.53}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-19 18:00:00'}, {'dt': 1781902800, 'main': {'temp': 304.47, 'feels_like': 307.19, 'temp_min': 304.47, 'temp_max': 304.47, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 54, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 92}, 'wind': {'speed': 5.57, 'deg': 234, 'gust': 6.79}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-19 21:00:00'}, {'dt': 1781913600, 'main': {'temp': 302.54, 'feels_like': 305.03, 'temp_min': 302.54, 'temp_max': 302.54, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 61, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 50}, 'wind': {'speed': 5.14, 'deg': 232, 'gust': 7.21}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-20 00:00:00'}, {'dt': 1781924400, 'main': {'temp': 304.26, 'feels_like': 307.25, 'temp_min': 304.26, 'temp_max': 304.26, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 7}, 'wind': {'speed': 5.57, 'deg': 239, 'gust': 7.42}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-20 03:00:00'}, {'dt': 1781935200, 'main': {'temp': 309.18, 'feels_like': 311.35, 'temp_min': 309.18, 'temp_max': 309.18, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 37, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 17}, 'wind': {'speed': 5.95, 'deg': 242, 'gust': 7.27}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-20 06:00:00'}, {'dt': 1781946000, 'main': {'temp': 313.14, 'feels_like': 314.22, 'temp_min': 313.14, 'temp_max': 313.14, 'pressure': 1003, 'sea_level': 1003, 'grnd_level': 998, 'humidity': 25, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.79, 'deg': 243, 'gust': 6.88}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-20 09:00:00'}, {'dt': 1781956800, 'main': {'temp': 311.5, 'feels_like': 314.73, 'temp_min': 311.5, 'temp_max': 311.5, 'pressure': 1002, 'sea_level': 1002, 'grnd_level': 997, 'humidity': 34, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 1}, 'wind': {'speed': 8.5, 'deg': 191, 'gust': 8.44}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-20 12:00:00'}, {'dt': 1781967600, 'main': {'temp': 306.87, 'feels_like': 311.26, 'temp_min': 306.87, 'temp_max': 306.87, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 3.35, 'deg': 165, 'gust': 4.76}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-20 15:00:00'}, {'dt': 1781978400, 'main': {'temp': 305.48, 'feels_like': 308.13, 'temp_min': 305.48, 'temp_max': 305.48, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 50, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.85, 'deg': 275, 'gust': 8.38}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-20 18:00:00'}, {'dt': 1781989200, 'main': {'temp': 303.73, 'feels_like': 306.46, 'temp_min': 303.73, 'temp_max': 303.73, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 57, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 7}, 'wind': {'speed': 3.9, 'deg': 264, 'gust': 7.56}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-20 21:00:00'}, {'dt': 1782000000, 'main': {'temp': 302.52, 'feels_like': 304.82, 'temp_min': 302.52, 'temp_max': 302.52, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 60, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 4}, 'wind': {'speed': 4.73, 'deg': 246, 'gust': 7.27}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-21 00:00:00'}, {'dt': 1782010800, 'main': {'temp': 304.12, 'feels_like': 306.33, 'temp_min': 304.12, 'temp_max': 304.12, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 53, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.44, 'deg': 245, 'gust': 7.05}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-21 03:00:00'}]

In [65]:
api_key="32b45e398e410de74bbb7bc204946c57"
url4=f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}"
response=requests.get(url4)
result=response.json()
print(json.dumps(result,indent=3))

{
   "coord": {
      "lon": 72.5801,
      "lat": 23.0215
   },
   "weather": [
      {
         "id": 800,
         "main": "Clear",
         "description": "clear sky",
         "icon": "01d"
      }
   ],
   "base": "stations",
   "main": {
      "temp": 308.33,
      "feels_like": 310.1,
      "temp_min": 308.33,
      "temp_max": 308.33,
      "pressure": 1008,
      "humidity": 38,
      "sea_level": 1008,
      "grnd_level": 1002
   },
   "visibility": 10000,
   "wind": {
      "speed": 4.51,
      "deg": 232,
      "gust": 5.02
   },
   "clouds": {
      "all": 2
   },
   "dt": 1781584568,
   "sys": {
      "country": "IN",
      "sunrise": 1781569445,
      "sunset": 1781618196
   },
   "timezone": 19800,
   "id": 1279233,
   "name": "Ahmedabad",
   "cod": 200
}

In [66]:
ws=result["wind"]["speed"]
print(ws)

4.51

# 374

In [68]:
# Write a Python program using beautiful soup to scrape all the news headlines in the div class “top news” from https://indianexpress.com/

import requests
from bs4 import BeautifulSoup

url="https://indianexpress.com/"
response=requests.get(url)
print(response.status_code)

200

In [69]:
response=response.text 
soup=BeautifulSoup(response,"html.parser") 
print(soup.prettify())

<!DOCTYPE html>
<html lang="en" xmlns:og="https://ogp.me/ns#">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=1300" name="viewport"/>
  <title>
   Latest News Today, Breaking News, India News, Top Headlines | The Indian Express
  </title>
  <meta content="163648403825" property="fb:pages">
   <meta content="168619349359" property="fb:pages">
    <meta content="185763818464532" property="fb:pages"/>
    <meta content="1494497934210205" property="fb:pages"/>
    <meta content="1774784956154724" property="fb:pages"/>
    <meta content="1567211863297748" property="fb:pages"/>
    <meta content="291465928041678" property="fb:pages"/>
    <meta content="339520043138547" property="fb:pages"/>
    <meta content="376556412852346" property="fb:pages"/>
    <meta content="215732349153100" property="fb:pages"/>
    <meta content="Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express." name="description"/>
    <meta content="News, Latest News, Breaking News, Live News, India News, News Online, News Headlines, News Today, English News, Top Stories" name="keywords"/>
    <meta content="website" property="og:type"/>
    <meta content="https://indianexpress.com/" property="og:url"/>
    <meta content="The Indian Express" property="og:site_name"/>
    <meta content="en_US" property="og:locale"/>
    <meta content="Latest News Today, Breaking News, India News, Top Headlines| The Indian Express" property="og:title"/>
    <meta content="Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express." property="og:description"/>
    <meta content="https://indianexpress.com/wp-content/themes/indianexpress/images/IE-OGimage.jpg" property="og:image"/>
    <meta content="image/jpeg" property="og:image:type"/>
    <meta content="1200" property="og:image:width"/>
    <meta content="667" property="og:image:height"/>
    <meta content="summary_large_image" name="twitter:card"/>
    <meta content="The Indian Express" name="twitter:site"/>
    <meta content="@indianexpress" name="twitter:creator">
     <meta content="https://indianexpress.com/" name="twitter:url"/>
     <meta content="Latest News Today, Breaking News, India News, Top Headlines| The Indian Express" name="twitter:title"/>
     <meta content="Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express." name="twitter:description"/>
     <meta content="https://indianexpress.com/wp-content/themes/indianexpress/images/IE-OGimage.jpg" property="twitter:image">
      <meta content="image/jpeg" property="twitter:image:type">
       <meta content="1200" property="twitter:image:width">
        <meta content="667" property="twitter:image:height">
         <meta content="en" itemprop="inLanguage"/>
         <meta content="Latest News Today, Breaking News, India News, Top Headlines| The Indian Express" itemprop="name"/>
         <meta content="https://indianexpress.com/" itemprop="mainEntityOfPage">
          <meta content="https://indianexpress.com/" itemprop="url"/>
          <meta content="Latest News Today, Breaking News, India News, Top Headlines| The Indian Express" itemprop="headline"/>
          <meta content="Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express." itemprop="description"/>
          <meta content="News, Latest News, Breaking News, Live News, India News, News Online, News Headlines, News Today, English News, Top Stories" itemprop="keywords"/>
          <script type="application/ld+json">
           {"@context":"https:\/\/schema.org","@type":"WebPage","name":"Latest News Today, Breaking News, India News, Top Headlines| The Indian Express","description":"Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express.","keywords":"News, Latest News, Breaking News, Live News, India News, News Online, News Headlines, News Today, English News, Top Stories","url":"https:\/\/indianexpress.com\/","mainContentOFPage":"News","inLanguage":"en","lastReviewed":"2026-06-16"}
          </script>
          <script type="application/ld+json">
           {
			"@context":"https://schema.org/",
			"@type":"ViewAction",
			"target":{
				"type":"EntryPoint",
				"urlTemplate":"https://indexpress.page.link/shareDL"
			}
		}
          </script>
          <meta content="00120a3a212c33eda15559fea6d0731769fd82f538180bd0a2dbe12991312ab4" name="ahrefs-site-verification"/>
          <meta content="NOODP" name="robots">
           <meta content="MJ12_ad7db024-a46c-482a-bb2f-e1ae09432a65" name="majestic-site-verification"/>
           <script>
            window.criteo_pubtag = window.criteo_pubtag || {};window.criteo_pubtag.disableSync = true;
           </script>
           <meta content="max-image-preview:large" name="robots">
            <style>
             img:is([sizes="auto" i], [sizes^="auto," i]) { contain-intrinsic-size: 3000px 1500px }
            </style>
            <script>
             let iersisAbtesting='yes';
			let iersCampName='v2-campaign-sub-1-4-20260514';
			let iersACohert=100;
			let iersShowAwsRegisteredUser='yes';
			let iersLoyaltyType='{"enable_aws_loyalty":"sessionLoyalty","casual":"1","repeat":"1","engaged":"1","loyal":"1","brandlover":"1"}';
			let iersCampNameRegistered='v2-campaign-reg-1-4-20260511';
			let iersACohertRegistered=50;
			let iersRemainingLoyaltyType='{"enable_aws_loyalty":"sessionLoyalty","casual":"1","repeat":"1","engaged":"1","loyal":"1","brandlover":"1"}';
			let iersCampNameRemainingRegistered='v2-campaign-reg-1-4-20260511';
			let iersACohertRemainingRegistered='50';
			let iersVersionSubscriber='sub-1.4';
			let iersVersion1Registered='reg-1.4';
			let iersVersion2Registered='reg-1.4';
			let iersPageLoadEvent ='yes';
			let iersShowAwsAnonymousUser='yes';
			let iersCampNameAnonymous='v2-campaign-ano-1-0-20260515';
			let iersACohertAnonymous='5';
			let iersVersionAnonymous='ano-1.0';
			let iersUserType="anonymous_user",iersVersion="",currentURLIers=window.location.href;var urlIers=new URL(currentURLIers),urlKeyIers=urlIers.searchParams.get("taboolatype");let iersRegisteredUsersLoyaltyPass=!1,iersNonLoyaltyRegisteredUser=!1,iersRegisterUser2_0=!1,iersABtestCase=!1,iersSavedSegmentName=iersGetWithExpiry("iers_segment_name"),iersSegmentName="",iersUserPlanDetails=[],iersUserDetails=!1,iersUserState="guest";null!==iersSavedSegmentName&&(iersSegmentName=iersSavedSegmentName.name);let iersSavedUserTopSections=iersGetWithExpiry("iers_user_top_sections"),iersUserTopSections=[];null!==iersSavedUserTopSections&&(iersUserTopSections=iersSavedUserTopSections.name);let iersLoggedinUserDetails=null,iers_allocation_done=!1,iers_isAwsUser=!1,iers_resolveAllocation=[];function iersIsAwsUsersList(){return new Promise(e=>{if(iers_allocation_done)return e(iers_isAwsUser);iers_resolveAllocation.push(e)})}function iersGlobalGetCookie(e){let r=e+"=",s=decodeURIComponent(document.cookie).split(";");for(let e=0;e<s.length;e++){let i=s[e];for(;" "==i.charAt(0);)i=i.substring(1);if(0==i.indexOf(r))return i.substring(r.length,i.length)}return""}function iersGlobalUndefinedCheck(e){let r=!1;return void 0!==e&&""!==e&&null!==e&&(r=!0),r}function iersCheckIfSubscriberAllowed(e){let r=!1;return!0===[10346934,209186,15268894,209185,203493,208633,208634,208635,208636,208637,208638,208639,208640,208641,208642,208643,208644,208645,208646,208648,208649,208650,13232261,14839323,3432583,10521544,8105709,785651,6805839,4726075,4382867,10095307,35,3640408,49,6591,19716,6564,8481,9415574,208807,13232532].includes(e)&&(r=!0),r}function iersCheckIfSubscriberEmailAllowed(e){return"string"==typeof e&&""!==e&&(e.endsWith("@indianexpress.com")||e.endsWith("@expressindia.com"))}function iersGetAlphaUsers(e,r){return(!0===iersCheckIfSubscriberAllowed(e)||!0===iersCheckIfSubscriberEmailAllowed(r))&&(iersUserType="alpha_user",!0)}async function iersIsAwsSubscriber(e){if(null!==iersLoggedinUserDetails){let e=iersHardcodedEmails(iersLoggedinUserDetails.user_email);if(!1!==e)return e}let r="subscriber_personalization",s=50;"undefined"!=typeof iersCampName&&iersCampName&&"undefined"!=typeof iersACohert&&iersACohert&&(r=iersCampName,s=iersACohert);let i=await iersassignVariantFromSsoid(e,s);return iersUserType="variant_personalize","B"===i&&(iersUserType="control_taboola"),null!=urlKeyIers&&""!==urlKeyIers&&(iersUserType="variant_personalize",i="A","control_taboola"===urlKeyIers&&(iersUserType="control_taboola",i="B")),i}function iersstr2ab(e){const r=new ArrayBuffer(e.length),s=new Uint8Array(r);for(let r=0;r<e.length;r++)s[r]=e.charCodeAt(r);return r}function iersab2hex(e){const r=[],s=new Uint8Array(e);for(let e=0;e<s.length;e++){const i=s[e].toString(16).padStart(2,"0");r.push(i)}return r.join("")}async function ierssha256Hex(e){return iersab2hex(await crypto.subtle.digest("SHA-256",iersstr2ab(e)))}async function iersassignVariantFromSsoid(e=null,r=10){if(r<0||r>100)throw new Error("percentageA must be between 0 and 100");let s=e?String(e).trim():"";return iersHexMod(await ierssha256Hex(s),100)<r?"A":"B"}function iersHexMod(e,r){let s=0;for(let i=0;i<e.length;i++)s=(16*s+parseInt(e[i],16))%r;return s}function iersGetVersion(){let e=iersGlobalGetCookie("ev_user_state"),r="";return"subscriber"===e?r=iersVersionSubscriber:"registered"===e?(r=iersVersion1Registered,!0===iersRegisterUser2_0&&(r=iersVersion2Registered)):"guest"===e&&(r=iersVersionAnonymous),iersVersion=r,r}function iersGetLoyaltyInfo(){let e=iersGlobalGetCookie("userLoyaltyBand"),r=!1;if(!0===iersGlobalUndefinedCheck(e))try{let s=JSON.parse(e);!0===iersGlobalUndefinedCheck(s)&&(s=JSON.parse(s),s&&"object"==typeof s&&(r={pvLoyalty:s.plb,sessionLoyalty:s.slb}))}catch(e){console.error("Unable to parse userLoyaltyBand",e)}return r}async function iersIsAwsRegisteredUser(e,r,s){if(null!==iersLoggedinUserDetails){let e=iersHardcodedEmails(iersLoggedinUserDetails.user_email);if(!1!==e)return e}let i=await iersassignVariantFromSsoid(e,s);return iersUserType="variant_personalize","B"===i&&(iersUserType="control_taboola"),null!=urlKeyIers&&""!==urlKeyIers&&(iersUserType="variant_personalize",i="A","control_taboola"===urlKeyIers&&(iersUserType="control_taboola",i="B")),i}function iersSetWithExpiry(e,r,s){const i={value:r,expiry:(new Date).getTime()+s};localStorage.setItem(e,JSON.stringify(i))}function iersGetWithExpiry(e){const r=localStorage.getItem(e);if(!r)return null;const s=JSON.parse(r);return(new Date).getTime()>s.expiry?(localStorage.removeItem(e),null):s.value}function iersHardcodedEmails(e){return"string"==typeof e&&""!==e&&void 0!==e&&("developregister@mailinator.com"===(e=e.toLowerCase())||"subscribeharshitpreprod@mailinator.com"===e?(iersUserType="variant_personalize","A"):("developregister1@mailinator.com"===e||"newsubscribepreprod@mailinator.com"===e)&&(iersUserType="control_taboola","B"))}window.addEventListener("iers_allocation_done",e=>{iers_allocation_done=!0,iers_resolveAllocation.length>0&&iers_resolveAllocation.forEach(function(e){e(iers_isAwsUser)})},{once:!0});
            </script>
            <link crossorigin="" href="https://fonts.gstatic.com/" rel="preconnect"/>
            <link href="https://www.googletagservices.com/" rel="preconnect">
             <link href="https://ads.pubmatic.com/" rel="preconnect"/>
             <link href="https://tpc.googlesyndication.com/" rel="preconnect"/>
             <link href="https://securepubads.g.doubleclick.net/" rel="preconnect"/>
             <link href="https://www.google.com/" rel="preconnect"/>
             <link href="https://googleads.g.doubleclick.net/" rel="preconnect"/>
             <link href="https://ads.pubmatic.com/" rel="preconnect"/>
             <link href="https://www.google-analytics.com/" rel="preconnect"/>
             <link href="https://apis.google.com/" rel="preconnect"/>
             <link href="https://www.googletagmanager.com/" rel="preconnect"/>
             <link href="https://cdn.moengage.com/" rel="preconnect"/>
             <link href="https://sb.scorecardresearch.com/" rel="preconnect"/>
             <link href="https://ua.indianexpress.com/" rel="preconnect"/>
             <link crossorigin="" href="https://fonts.gstatic.com/" rel="dns-prefetch"/>
             <link href="https://www.googletagservices.com/" rel="dns-prefetch">
              <link href="https://ads.pubmatic.com/" rel="dns-prefetch"/>
              <link href="https://tpc.googlesyndication.com/" rel="dns-prefetch"/>
              <link href="https://securepubads.g.doubleclick.net/" rel="dns-prefetch"/>
              <link href="https://www.google.com/" rel="dns-prefetch"/>
              <link href="https://googleads.g.doubleclick.net/" rel="dns-prefetch"/>
              <link href="https://ads.pubmatic.com/" rel="dns-prefetch"/>
              <link href="https://www.google-analytics.com/" rel="dns-prefetch"/>
              <link href="https://apis.google.com/" rel="dns-prefetch"/>
              <link href="https://www.googletagmanager.com/" rel="dns-prefetch"/>
              <link href="https://cdn.moengage.com/" rel="dns-prefetch"/>
              <link href="https://sb.scorecardresearch.com/" rel="dns-prefetch"/>
              <link href="https://ua.indianexpress.com/" rel="dns-prefetch"/>
              <link href="https://rtbcdn.andbeyond.media" rel="preconnect"/>
              <link href="https://rtbcdn.andbeyond.media" rel="dns-prefetch"/>
              <link href="https://rtbpass-us.andbeyond.media" rel="preconnect"/>
              <link href="https://rtbpass-us.andbeyond.media" rel="dns-prefetch"/>
              <link crossorigin="" href="https://cdn.taboola.com" rel="preconnect"/>
              <link href="//cdn.taboola.com" rel="dns-prefetch"/>
              <link href="https://static.chartbeat.com/" rel="preconnect"/>
              <link href="https://static.chartbeat.com/" rel="dns-prefetch"/>
              <link as="font" crossorigin="" href="https://fonts.gstatic.com/s/ptserif/v18/EJRVQgYoZZY2vCFuvAFWzr8.woff2" rel="preload" type="font/woff2"/>
              <link as="font" crossorigin="" href="https://fonts.gstatic.com/s/roboto/v47/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmUiAo.woff2" rel="preload" type="font/woff2"/>
              <link as="font" crossorigin="" href="https://fonts.gstatic.com/s/ptserif/v18/EJRSQgYoZZY2vCFuvAnt66qSVys.woff2" rel="preload" type="font/woff2"/>
              <link as="font" crossorigin="" href="https://fonts.gstatic.com/s/roboto/v47/KFO7CnqEu92Fr1ME7kSn66aGLdTylUAMa3yUBHMdazQ.woff2" rel="preload" type="font/woff2"/>
              <style>
               @font-face{font-family:'PT Serif';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/ptserif/v18/EJRVQgYoZZY2vCFuvAFWzr8.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:Roboto;font-style:normal;font-weight:700;font-stretch:100%;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v47/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmUiAo.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:'PT Serif';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/ptserif/v18/EJRSQgYoZZY2vCFuvAnt66qSVys.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:Roboto;font-style:normal;font-weight:400;font-stretch:100%;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v47/KFO7CnqEu92Fr1ME7kSn66aGLdTylUAMa3yUBHMdazQ.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}
              </style>
              <!-- Jetpack Site Verification Tags -->
              <meta content="GksxYjGFLX8yIx8g5v-Jg5XueVMsv23jAO2UE8hpetM" name="google-site-verification">
               <meta content="CCA9DA5B985004F4462DA743E776C636" name="msvalidate.01"/>
               <style data-id="inline-css-060620261621" type="text/css">
                @charset 'UTF-8';

In [73]:
a=soup.find("div",class_="wp-block-template-part").find("div",class_="breaking-flex")
b=soup.find("div",class_="breking-big-text").find("h1",class_="o-breaking-news__title ts-3").text.strip()

print(b)

Trump says Iran ‘has agreed to never have a nuclear weapon’

# 375

In [75]:
# Write a program for web scrapping using BeautifulSoup to scrape the following details from the given 
# link and make a data frame using that scraped data from the page in a given link.
# Link: https://www.politifact.com/factchecks
# You will find 30 news articles with fact checks on this page. You need to scrape the following details 
# from all the articles and store that in a data frame. Statement of News, Date of News, Source of News. 



import requests
from bs4 import BeautifulSoup

url="https://www.politifact.com/factchecks"
response=requests.get(url)
print(response.status_code)
response=response.text 
soup=BeautifulSoup(response,"html.parser") 
# print(soup.prettify())

200

In [87]:
a=soup.find("div",class_="o-listicle__inner").find_all("li",class_="o-listicle__item")
news=[]
date=[]
source=[]
for i in a:
    news.append(i.find("div",class_="m-statement__quote").find("a",href=True).text.strip())
    d=i.find("footer",class_="m-statement__footer").text.strip()
    d1=d.split("•")
    date.append(d1[1])
    source.append(i.find("div",class_="m-statement__desc").text.strip())

import pandas as pd

df=pd.DataFrame({"News ":news , "Date ":date,"Source ":source})
df

,News,Date,Source
0,“Michelle Obama is a man.”,"June 15, 2026","stated on June 14, 2026 in a UFC event at the ..."
1,“If you live near one of these large data cent...,"June 12, 2026","stated on June 5, 2026 in an X post:"
2,“No Republican wins in Nassau.”,"June 12, 2026","stated on May 22, 2026 in remarks in Suffern, ..."
3,Sen. Susan Collins votes “with Donald Trump 95...,"June 10, 2026","stated on June 9, 2026 in a primary night speech:"
4,The ongoing ballot counting in California mean...,"June 8, 2026","stated on June 7, 2026 in an interview on NBC'..."
5,Los Angeles mayoral candidate Spencer Pratt “g...,"June 8, 2026","stated on June 4, 2026 in X posts:"
6,This video shows a June 2026 earthquake in the...,"June 8, 2026","stated on June 7, 2026 in an X post:"
7,This image shows a person stuffing ballots int...,"June 8, 2026","stated on June 5, 2026 in social media posts:"
8,Los Angeles mayoral candidate Nithya Raman had...,"June 8, 2026","stated on June 7, 2026 in X posts:"
9,Iowa Democratic U.S. Senate candidate Josh Tur...,"June 5, 2026","stated on June 2, 2026 in an ad:"
10,"""The number of New Yorkers who consume cannabi...","June 5, 2026","stated on April 2, 2026 in an interview with P..."
11,"""Michigan has spent more than $2.5 billion on ...","June 4, 2026","stated on May 28, 2026 in a Democratic primary..."
12,“Adam Hoffman abused a little boy” and Ken Pax...,"June 3, 2026","stated on May 28, 2026 in an X post:"
13,Says his cognitive test results showed he has ...,"June 3, 2026","stated on May 31, 2026 in a Truth Social post:"
14,A video shows workers removing President Donal...,"June 1, 2026","stated on May 31, 2026 in social media posts:"
15,El presidente Donald Trump firmó una ley para ...,"May 28, 2026","stated on May 27, 2026 in una publicación en T..."
16,Democratic Texas U.S. Senate candidate James T...,"May 28, 2026","stated on May 27, 2026 in an ad:"
17,Democratic Texas U.S. Senate candidate James T...,"May 27, 2026","stated on May 26, 2026 in a primary election v..."
18,“The reason (people in Cuba) are forced to sur...,"May 22, 2026","stated on May 20, 2026 in an X post:"
19,“President Trump’s tariffs are costing New Yor...,"May 21, 2026","stated on March 19, 2026 in a press release:"
20,"""There's been numerous other occasions over th...","May 20, 2026","stated on May 18, 2026 in remarks at the White..."
21,“San Diego mosque shooters identified as trans...,"May 20, 2026","stated on May 19, 2026 in in social media posts:"
22,"Video shows U.S. Rep. Byron Donalds saying, “I...","May 15, 2026","stated on May 14, 2026 in X posts:"
23,An American passenger on the cruise ship invol...,"May 14, 2026","stated on May 6, 2026 in an X post:"
24,“Florida is the only state in the nation kicki...,"May 14, 2026","stated on April 29, 2026 in an X post:"
25,"In 2020, “Amy Acton called off Ohio’s election...","May 13, 2026","stated on April 24, 2026 in an ad:"
26,Imágenes muestran a personas “infectadas con H...,"May 13, 2026","stated on May 8, 2026 in una publicación en Ti..."
27,"“Today, there are more children sleeping in Ne...","May 11, 2026","stated on March 5, 2026 in a press release:"
28,“The average IRS tax refund is up 11% compared...,"May 11, 2026","stated on March 31, 2026 in an X post:"
29,Gasoline prices have “come down very substanti...,"May 8, 2026","stated on May 7, 2026 in remarks to reporters:"

# 376

In [89]:
# Write a program of web scrapping using BeautifulSoup to scrape the given data from the following link.
# https://editorial.rottentomatoes.com/guide/popular-movies/
# On the above link, you’ll find 30 Popular movies. Scrape the Movie Title and Rating of that particular movie and make a Dataframe of the same.


import requests
from bs4 import BeautifulSoup

url="https://editorial.rottentomatoes.com/guide/popular-movies/"
response=requests.get(url)
print(response.status_code)
response=response.text 
soup=BeautifulSoup(response,"html.parser") 
# print(soup.prettify())

200

In [90]:
a=soup.find("div",class_="content-body").find_all("div",class_="block-countdown rkv-block")
name=[]
rat=[]
for i in a:
    name.append(i.find("div",class_="meta-title-wrapper").find("a",class_="meta-title").text.strip())
    rat.append(i.find("div",class_="meta-scores-wrapper").find("span",class_="tMeterScore").text.strip())

import pandas as pd

df=pd.DataFrame({"Name":name , "Ratting ":rat})
df

                                        Name Ratting
0                                Scary Movie      24%
1                    Masters of the Universe      68%
2                                  Backrooms      88%
3                                  Obsession      94%
4                                      Hokum      90%
5                                   Pressure      86%
6       Star Wars: The Mandalorian and Grogu      62%
7                          Project Hail Mary      94%
8   The Amazing Digital Circus: The Last Act      - -
9                             Office Romance      48%
10                            Disclosure Day      81%
11                           The Breadwinner      20%
12                                   Michael      38%
13                      The Perfect Neighbor      99%
14                               In the Grey      49%
15                              Power Ballad      87%
16                                     Tuner      94%
17                                 Send Help      92%
18                                    Exit 8      93%
19                      The Sheep Detectives      95%
20                                 Iron Lung      59%
21                                   Hoppers      94%
22                              Ladies First      25%
23                               The Furious      97%
24                                 Passenger      48%
25               Remarkably Bright Creatures      84%
26                                   I Swear      97%
27                                      Apex      67%
28                           Dead Man's Wire      91%
29                                 Is God Is      97%

# 377

In [92]:
# 377		Write a Python program to find the title tags from a given html document. html_doc = """ <html> <head>
# <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
# <title>An example of HTML page</title> </head>
# <body>
# <h2>This is an example HTML page</h2>
# <p>
# Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at nisi velit, aliquet iaculis est. Curabitur porttitor nisi vel lacus euismod egestas. In hac habitasse platea dictumst. In sagittis magna eu odio interdum mollis. Phasellus sagittis pulvinar facilisis. Donec vel odio volutpat tortor volutpat commodo. Donec vehicula vulputate sem, vel iaculis urna molestie eget. Sed pellentesque adipiscing tortor, at condimentum elit elementum sed. Mauris dignissim elementum nunc, non elementum felis condimentum eu. In in turpis quis erat imperdiet vulputate. Pellentesque mauris turpis, dignissim sed iaculis eu, euismod eget ipsum. Vivamus mollis adipiscing viverra. Morbi at sem eget nisl euismod porta.</p>
# <p><a href="https://www.w3resource.com/html/HTML-tutorials.php">Learn HTML from w3resource.com</a></p>
# <p><a href="https://www.w3resource.com/css/CSS-tutorials.php">Learn CSS from w3resource.com</a></p>
# </body>
# </html>
# """		3					



html_doc = """ <html> <head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>An example of HTML page</title> </head>
<body>
<h2>This is an example HTML page</h2>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at nisi velit, aliquet iaculis est. Curabitur porttitor nisi vel lacus euismod egestas. In hac habitasse platea dictumst. In sagittis magna eu odio interdum mollis. Phasellus sagittis pulvinar facilisis. Donec vel odio volutpat tortor volutpat commodo. Donec vehicula vulputate sem, vel iaculis urna molestie eget. Sed pellentesque adipiscing tortor, at condimentum elit elementum sed. Mauris dignissim elementum nunc, non elementum felis condimentum eu. In in turpis quis erat imperdiet vulputate. Pellentesque mauris turpis, dignissim sed iaculis eu, euismod eget ipsum. Vivamus mollis adipiscing viverra. Morbi at sem eget nisl euismod porta.</p>
<p><a href="https://www.w3resource.com/html/HTML-tutorials.php">Learn HTML from w3resource.com</a></p>
<p><a href="https://www.w3resource.com/css/CSS-tutorials.php">Learn CSS from w3resource.com</a></p>
</body>
</html>
"""

from bs4 import BeautifulSoup
import pandas as pd

soup=BeautifulSoup(html_doc,"html.parser")

In [93]:
t=soup.find("title").text.strip()
print(t)

An example of HTML page

# 378

In [94]:

html_doc = """ <html> <head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>An example of HTML page</title> </head>
<body>
<h2>This is an example HTML page</h2>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at nisi velit, aliquet iaculis est. Curabitur porttitor nisi vel lacus euismod egestas. In hac habitasse platea dictumst. In sagittis magna eu odio interdum mollis. Phasellus sagittis pulvinar facilisis. Donec vel odio volutpat tortor volutpat commodo. Donec vehicula vulputate sem, vel iaculis urna molestie eget. Sed pellentesque adipiscing tortor, at condimentum elit elementum sed. Mauris dignissim
elementum nunc, non elementum felis condimentum eu. In in turpis quis erat imperdiet vulputate. Pellentesque mauris turpis, dignissim sed iaculis eu, euismod eget ipsum. Vivamus mollis adipiscing viverra. Morbi at sem eget nisl euismod porta.</p>
<p><a href="https://www.w3resource.com/html/HTML-tutorials.php">Learn HTML from w3resource.com</a></p>
<p><a href="https://www.w3resource.com/css/CSS-tutorials.php">Learn CSS from w3resource.com</a></p>
</body>
</html>
"""

from bs4 import BeautifulSoup
import pandas as pd

soup=BeautifulSoup(html_doc,"html.parser")

In [96]:
p=soup.find_all("p")
print(p)

[<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at nisi velit, aliquet iaculis est. Curabitur porttitor nisi vel lacus euismod egestas. In hac habitasse platea dictumst. In sagittis magna eu odio interdum mollis. Phasellus sagittis pulvinar facilisis. Donec vel odio volutpat tortor volutpat commodo. Donec vehicula vulputate sem, vel iaculis urna molestie eget. Sed pellentesque adipiscing tortor, at condimentum elit elementum sed. Mauris dignissim
elementum nunc, non elementum felis condimentum eu. In in turpis quis erat imperdiet vulputate. Pellentesque mauris turpis, dignissim sed iaculis eu, euismod eget ipsum. Vivamus mollis adipiscing viverra. Morbi at sem eget nisl euismod porta.</p>, <p><a href="https://www.w3resource.com/html/HTML-tutorials.php">Learn HTML from w3resource.com</a></p>, <p><a href="https://www.w3resource.com/css/CSS-tutorials.php">Learn CSS from w3resource.com</a></p>]

In [97]:
a=[]
for i in range(len(p)):
    pra=p[i].get_text().strip()
    a.append(pra)
print(a)

['Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at nisi velit, aliquet iaculis est. Curabitur porttitor nisi vel lacus euismod egestas. In hac habitasse platea dictumst. In sagittis magna eu odio interdum mollis. Phasellus sagittis pulvinar facilisis. Donec vel odio volutpat tortor volutpat commodo. Donec vehicula vulputate sem, vel iaculis urna molestie eget. Sed pellentesque adipiscing tortor, at condimentum elit elementum sed. Mauris dignissim\nelementum nunc, non elementum felis condimentum eu. In in turpis quis erat imperdiet vulputate. Pellentesque mauris turpis, dignissim sed iaculis eu, euismod eget ipsum. Vivamus mollis adipiscing viverra. Morbi at sem eget nisl euismod porta.', 'Learn HTML from w3resource.com', 'Learn CSS from w3resource.com']

# 378

In [98]:
html_doc = """ <html> <head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>An example of HTML page</title> </head>
<body>
<h2>This is an example HTML page</h2>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at nisi velit, aliquet iaculis est. Curabitur porttitor nisi vel lacus euismod egestas. In hac habitasse platea dictumst. In sagittis magna eu odio interdum mollis. Phasellus sagittis pulvinar facilisis. Donec vel odio volutpat tortor volutpat commodo. Donec vehicula vulputate sem, vel iaculis urna molestie eget. Sed pellentesque adipiscing tortor, at condimentum elit elementum sed. Mauris dignissim
elementum nunc, non elementum felis condimentum eu. In in turpis quis erat imperdiet vulputate. Pellentesque mauris turpis, dignissim sed iaculis eu, euismod eget ipsum. Vivamus mollis adipiscing viverra. Morbi at sem eget nisl euismod porta.</p>
<p><a href="https://www.w3resource.com/html/HTML-tutorials.php">Learn HTML from w3resource.com</a></p>
<p><a href="https://www.w3resource.com/css/CSS-tutorials.php">Learn CSS from w3resource.com</a></p>
</body>
</html>
"""
from bs4 import BeautifulSoup
import pandas as pd

soup=BeautifulSoup(html_doc,"html.parser")

In [103]:
p=soup.find_all("p")
print(len(p))

3

# 385

In [104]:
# Write a Python program to extract all the URLs from the webpage python.org that are nested within <li> tags from.



import requests
from bs4 import BeautifulSoup

url="https://www.python.org/"
response=requests.get(url)
print(response.status_code)
response=response.text 
soup=BeautifulSoup(response,"html.parser") 
# print(soup.prettify())

200

In [113]:
a=soup.find("div",class_="container").find_all("li")
b=soup.find_all("a",href=True)

In [115]:
link=[]
for i in b:
    l=i.get("href")
    link.append(l)
print(link)
print(len(link))

['#content', '#python-network', '/', 'https://www.python.org/psf/', 'https://docs.python.org', 'https://pypi.org/', '/jobs/', '/community/', '#top', '/', 'https://donate.python.org/', '#site-map', '#', 'javascript:;', 'javascript:;', 'javascript:;', '#', 'https://www.linkedin.com/company/python-software-foundation/', 'https://fosstodon.org/@ThePSF', '/community/irc/', 'https://twitter.com/ThePSF', '/about/', '/about/apps/', '/about/quotes/', '/about/gettingstarted/', '/about/help/', 'http://brochure.getpython.info/', '/downloads/', '/downloads/', '/downloads/source/', '/downloads/windows/', '/downloads/macos/', '/downloads/android/', '/download/other/', 'https://docs.python.org/3/license.html', '/download/alternatives', '/doc/', '/doc/', '/doc/av', 'https://wiki.python.org/moin/BeginnersGuide', 'https://docs.python.org/3/faq/', 'https://translations.python.org/', 'https://peps.python.org', 'https://wiki.python.org/moin/PythonBooks', '/doc/essays/', '/community/', '/community/diversity/', '/community/lists/', '/community/irc/', '/community/forums/', '/psf/annual-report/2024/', '/community/workshops/', '/community/sigs/', '/community/logos/', 'https://wiki.python.org/moin/', '/psf/conduct/', '/community/awards', '/psf/get-involved/', '/psf/community-stories/', '/success-stories/', '/success-stories/category/arts/', '/success-stories/category/business/', '/success-stories/category/education/', '/success-stories/category/engineering/', '/success-stories/category/government/', '/success-stories/category/scientific/', '/success-stories/category/software-development/', '/blogs/', '/blogs/', '/psf/newsletter/', 'http://pyfound.blogspot.com/', 'http://pycon.blogspot.com/', 'http://planetpython.org/', '/events/', '/events/python-events/', '/events/python-user-group/', '/events/python-events/past/', '/events/python-user-group/past/', 'https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_Event', '/shell/', 'http://docs.python.org/3/tutorial/introduction.html#using-python-as-a-calculator', '//docs.python.org/3/tutorial/introduction.html#lists', '//docs.python.org/3/tutorial/controlflow.html', '//docs.python.org/3/tutorial/controlflow.html#defining-functions', '//docs.python.org/3/tutorial/', '/doc/', '/about/gettingstarted/', '/downloads/release/python-3146/', 'https://docs.python.org', '//jobs.python.org', 'https://blog.python.org', 'https://blog.python.org/2026/06/python-3146-31314/', 'https://pyfound.blogspot.com/2026/06/psf-strategic-plan-2026-draft-open-for.html', 'https://pyfound.blogspot.com/2026/06/no-starch-press-humble-bundle-grab-deal.html', 'https://blog.python.org/2026/06/python-3150-beta-2/', 'https://pyfound.blogspot.com/2026/05/psf-welcomes-hudson-river-trading-hrt.html', '/events/calendars/', '/events/python-user-group/2170/', '/events/python-events/2173/', '/events/python-events/2178/', '/events/python-events/2148/', '/events/python-events/2141/', '/success-stories/', '/success-stories/zama-concrete-ml-simplifying-homomorphic-encryption-for-python-machine-learning/', '/success-stories/zama-concrete-ml-simplifying-homomorphic-encryption-for-python-machine-learning/', '/about/apps', 'https://www.djangoproject.com/', 'https://trypyramid.com/', 'https://bottlepy.org', 'https://www.tornadoweb.org/', 'https://flask.palletsprojects.com/', 'https://litestar.dev/', 'https://fastapi.tiangolo.com/', 'https://en.wikipedia.org/wiki/Tkinter', 'https://pygobject.gnome.org/', 'https://riverbankcomputing.com/software/pyqt/intro', 'https://wiki.qt.io/Qt_for_Python', 'https://kivy.org/', 'https://www.wxpython.org/', 'https://dearpygui.readthedocs.io/en/latest/', 'https://pytorch.org/', 'https://www.tensorflow.org/', 'https://scikit-learn.org/', 'https://huggingface.co/docs/transformers/', 'https://docs.anthropic.com/', 'https://langchain.com/', 'https://scipy.org/', 'https://pandas.pydata.org/', 'https://ipython.org/', 'https://buildbot.net/', 'https://trac.edgewall.org/', 'https://www.roundup-tracker.org/', 'https://docs.ansible.com/', 'https://saltproject.io/', 'https://www.openstack.org/', 'https://xon.sh/', '/psf/', '/psf/', '/psf/membership/', '/psf/donations/', '#python-network', '/about/', '/about/apps/', '/about/quotes/', '/about/gettingstarted/', '/about/help/', 'http://brochure.getpython.info/', '/downloads/', '/downloads/', '/downloads/source/', '/downloads/windows/', '/downloads/macos/', '/downloads/android/', '/download/other/', 'https://docs.python.org/3/license.html', '/download/alternatives', '/doc/', '/doc/', '/doc/av', 'https://wiki.python.org/moin/BeginnersGuide', 'https://docs.python.org/3/faq/', 'https://translations.python.org/', 'https://peps.python.org', 'https://wiki.python.org/moin/PythonBooks', '/doc/essays/', '/community/', '/community/diversity/', '/community/lists/', '/community/irc/', '/community/forums/', '/psf/annual-report/2024/', '/community/workshops/', '/community/sigs/', '/community/logos/', 'https://wiki.python.org/moin/', '/psf/conduct/', '/community/awards', '/psf/get-involved/', '/psf/community-stories/', '/success-stories/', '/success-stories/category/arts/', '/success-stories/category/business/', '/success-stories/category/education/', '/success-stories/category/engineering/', '/success-stories/category/government/', '/success-stories/category/scientific/', '/success-stories/category/software-development/', '/blogs/', '/blogs/', '/psf/newsletter/', 'http://pyfound.blogspot.com/', 'http://pycon.blogspot.com/', 'http://planetpython.org/', '/events/', '/events/python-events/', '/events/python-user-group/', '/events/python-events/past/', '/events/python-user-group/past/', 'https://wiki.python.org/moin/PythonEventsCalendar#Submitting_an_Event', '/dev/', 'https://devguide.python.org/', 'https://github.com/python/cpython/issues', 'https://mail.python.org/mailman/listinfo/python-dev', '/dev/core-mentorship/', '/dev/security/', '#python-network', '/about/help/', '/community/diversity/', 'https://github.com/python/pythondotorg/issues', 'https://status.python.org/', '/psf-landing/', '/about/legal/', 'https://policies.python.org/python.org/Privacy-Notice/']
213

# 386

In [119]:
# Write a Python program to find all the h2 tags and list the first four from the webpage python.org
h2=[]
h=soup.find_all("h2")
h2.append(h)
print(h2[0:4])

[[<h2 class="widget-title"><span aria-hidden="true" class="icon-get-started"></span>Get Started</h2>, <h2 class="widget-title"><span aria-hidden="true" class="icon-download"></span>Download</h2>, <h2 class="widget-title"><span aria-hidden="true" class="icon-documentation"></span>Docs</h2>, <h2 class="widget-title"><span aria-hidden="true" class="icon-jobs"></span>Jobs</h2>, <h2 class="widget-title"><span aria-hidden="true" class="icon-news"></span>Latest News</h2>, <h2 class="widget-title"><span aria-hidden="true" class="icon-calendar"></span>Upcoming Events</h2>, <h2 class="widget-title"><span aria-hidden="true" class="icon-success-stories"></span>Success Stories</h2>, <h2 class="widget-title"><span aria-hidden="true" class="icon-python"></span>Use Python for…</h2>, <h2 class="widget-title">
<span class="prompt">&gt;&gt;&gt;</span> <a href="/psf/">Python Software Foundation</a>
</h2>]]

# 388

In [120]:
# Write a Python program to a list of all the h1, h2, h3 tags from the webpage python.org. 

h1=[]
h3=[]

H1=soup.find_all("h1")
H3=soup.find_all("h3")
h1.append(H1)
h3.append(H3)
print(h1)
print(h3)

[[<h1>Intuitive Interpretation</h1>, <h1>Compound Data Types</h1>, <h1>All the Flow You’d Expect</h1>, <h1>Functions Defined</h1>, <h1>Quick &amp; Easy to Learn</h1>]]
[[]]

# 389

In [121]:
# Write a Python program to extract all the text from a given web page python.org. 

body=soup.find("body").text.strip()
print(body)

Notice: This page displays a fallback because interactive scripts did not run. Possible causes include disabled JavaScript or failure to load scripts or stylesheets.





Skip to content


▼ Close



Python


PSF


Docs


PyPI


Jobs


Community



▲ The Python Network










Donate

≡ Menu


Search This Site


                                    GO





A A

Smaller
Larger
Reset






Socialize

LinkedIn
Mastodon
Chat on IRC
Twitter










About

Applications
Quotes
Getting Started
Help
Python Brochure



Downloads

All releases
Source code
Windows
macOS
Android
Other Platforms
License
Alternative Implementations



Documentation

Docs
Audio/Visual Talks
Beginner's Guide
FAQ
Non-English Docs
PEP Index
Python Books
Python Essays



Community

Diversity
Mailing Lists
IRC
Forums
PSF Annual Impact Report
Python Conferences
Special Interest Groups
Python Logo
Python Wiki
Code of Conduct
Community Awards
Get Involved
Shared Stories



Success Stories

Arts
Business
Education
Engineering
Government
Scientific
Software Development



News

Python News
PSF Newsletter
PSF News
PyCon US News
News from the Community



Events

Python Events
User Group Events
Python Events Archive
User Group Events Archive
Submit an Event








>_
                        Launch Interactive Shell





# Simple arithmetic
>>> 1 / 2
0.5
>>> 2 ** 3
8
>>> 17 / 3  # true division returns a float
5.666666666666667
>>> 17 // 3  # floor division
5

Intuitive Interpretation
Calculations are simple with Python, and expression syntax is straightforward: the operators +, -, * and / work as expected; parentheses () can be used for grouping. More about simple math functions in Python 3.


# Python 3: List comprehensions
>>> fruits = ['Banana', 'Apple', 'Lime']
>>> loud_fruits = [fruit.upper() for fruit in fruits]
>>> print(loud_fruits)
['BANANA', 'APPLE', 'LIME']

# List and the enumerate function
>>> list(enumerate(fruits))
[(0, 'Banana'), (1, 'Apple'), (2, 'Lime')]

Compound Data Types
Lists (known as arrays in other languages) are one of the compound data types that Python understands. Lists can be indexed, sliced and manipulated with other built-in functions. More about lists in Python 3


# For loop on a list
>>> numbers = [2, 4, 6, 8]
>>> product = 1
>>> for number in numbers:
...    product = product * number
...
>>> print('The product is:', product)
The product is: 384

All the Flow You’d Expect
Python knows the usual control flow statements that other languages speak — if, for, while and range — with some of its own twists, of course. More control flow tools in Python 3


# Python 3: Fibonacci series up to n
>>> def fib(n):
>>>     a, b = 0, 1
>>>     while a < n:
>>>         print(a, end=' ')
>>>         a, b = b, a+b
>>>     print()
>>> fib(1000)
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987

Functions Defined
The core of extensible programming is defining functions. Python allows mandatory and optional arguments, keyword arguments, and even arbitrary argument lists. More about defining functions in Python 3


# Simple output (with Unicode)
>>> print("Hello, I'm Python!")
Hello, I'm Python!

# Input, assignment
>>> name = input('What is your name?\n')
>>> print(f'Hi, {name}.')
What is your name?
Python
Hi, Python.

Quick & Easy to Learn
Experienced programmers in any other language can pick up Python very quickly, and beginners find the clean syntax and indentation structure easy to learn. Whet your appetite with our Python 3 overview.





Python is a programming language that lets you work quickly and integrate systems more effectively. Learn More









Get Started
Whether you're new to programming or an experienced developer, it's easy to learn and use Python.
Start with our Beginner’s Guide


Download
Python source code and installers are available for download for all versions!
Latest: Python 3.14.6


Docs
Documentation for Python's standard library, along with tutorials and guides, are available online.
docs.python.org


Jobs
Looking for work or have a Python related position that you're trying to hire for? Our relaunched community-run job board is the place to go.
jobs.python.org





Latest News
More


2026-06-10
Python 3.14.6 and 3.13.14 are now available!

2026-06-04
PSF Strategic Plan 2026 Draft: Open for Community Feedback

2026-06-02
No Starch Press Humble Bundle: Grab a Deal and Support the PSF!

2026-06-02
Python 3.15.0 beta 2 is here!

2026-05-13
PSF Welcomes Hudson River Trading (HRT) as a Visionary Sponsor





Upcoming Events
More


2026-06-18
Python for (Almost) Everything

2026-06-19
PyCon Singapore 2026

2026-07-03
Python Norte 2026

2026-07-13
SciPy 2026

2026-07-13
EuroPython 2026







Success Stories
More


To simplify the adoption of FHE, which involves a complex and resource-intensive technological stack, Zama developed tools that streamline the integration of FHE into applications. Since Python is the de facto standard for building machine learning (ML) applications, it was an obvious choice to create an open-source FHE library in Python.




Zama Concrete ML: Simplifying Homomorphic Encryption for Python Machine Learning by Andrei Stoian and Benoit Chevallier-Mames








Use Python for…
More

Web Development:
        Django, Pyramid, Bottle, Tornado, Flask, Litestar, FastAPI
GUI Development:
        tkInter, PyGObject, PyQt, PySide, Kivy, wxPython, DearPyGui
AI and Machine Learning:
        PyTorch, TensorFlow, scikit-learn, Transformers, Anthropic, LangChain
Scientific and Numeric:
        SciPy, Pandas, IPython
Software Development:
        Buildbot, Trac, Roundup
System Administration:
        Ansible, Salt, OpenStack, xonsh







>>> Python Software Foundation

The mission of the Python Software Foundation is to promote, protect, and advance the Python programming language, and to support and facilitate the growth of a diverse and international community of Python programmers. Learn more

Become a Member
Donate to the PSF









▲ Back to Top


About

Applications
Quotes
Getting Started
Help
Python Brochure



Downloads

All releases
Source code
Windows
macOS
Android
Other Platforms
License
Alternative Implementations



Documentation

Docs
Audio/Visual Talks
Beginner's Guide
FAQ
Non-English Docs
PEP Index
Python Books
Python Essays



Community

Diversity
Mailing Lists
IRC
Forums
PSF Annual Impact Report
Python Conferences
Special Interest Groups
Python Logo
Python Wiki
Code of Conduct
Community Awards
Get Involved
Shared Stories



Success Stories

Arts
Business
Education
Engineering
Government
Scientific
Software Development



News

Python News
PSF Newsletter
PSF News
PyCon US News
News from the Community



Events

Python Events
User Group Events
Python Events Archive
User Group Events Archive
Submit an Event



Contributing

Developer's Guide
Issue Tracker
python-dev list
Core Mentorship
Report a Security Issue



▲ Back to Top





Help & General Contact
Diversity Initiatives
Submit Website Bug

Status




Copyright ©2001-2026.
                             Python Software Foundation
                             Legal Statements
                             Privacy Notice

# 395

In [126]:
#  Write a python code to scrape data from the file ‘imdb.html’, the file contains the list of upcoming movies to be released in India
#  in year 2023 and 2024. Scrape the data to get the movie name and year. Create a DataFrame having columns containing movie
#  name and year.


# The dataset provided in ‘kc_house_data.csv’ contains house sale prices for King County, which includes Seattle. It includes
# homes sold between May 2014 and May 2015Perform the following tasks :
# 1) Load the csv to a dataframe named ‘house_survey’.
# 2) Display the first 5 rows of the dataframe.
# 3) Drop the columns "id" and "Unnamed: 0"
# 4) Check all the null values present in all the columns of the dataframe.
# 5) Fill the missing values of the column 'bedrooms' with the mean of the column.
# 6) Fill the missing values of the column 'bathrooms' with the mean of the column.
# 7) Use the Pandas method corr() to find the feature other than price that is most correlated with price and mention your answer
# as a comment.
# 8) Fit a linear regression model to predict the 'price' using the list of features:
# ["floors", "waterfront","lat" ,"bedrooms" ,"sqft_basement" ,"view" ,"bathrooms","sqft_living15"
# ,"sqft_above","grade","sqft_living"]
# 9) Consider 30% testing samples and use random state 10.
# 10) Find the Mean Squared Error.

In [125]:
from bs4 import BeautifulSoup
import pandas as pd

file=open("imdb.html",encoding="utf-8")
response=file.read()
soup=BeautifulSoup(response,"html.parser")
# soup=soup.prettify()
# print(soup)

In [137]:
a=soup.find("div",class_="lister list detail sub-list").find_all("div",class_="lister-item mode-advanced")
name=[]
year=[]
for i in  a:
    n=soup.find("div",class_="lister-item-content").find("a").text.strip()
    name.append(n)
    y=soup.find("div",class_="lister-item-content").find("span",class_="lister-item-year text-muted unbold").text.strip()
    y1=y[-5:-1]
    year.append(y1)
    
import pandas as pd

df=pd.DataFrame({"Movie":name , "Year ":year})
df

            Movie Year
0   Black Panther  2018
1   Black Panther  2018
2   Black Panther  2018
3   Black Panther  2018
4   Black Panther  2018
5   Black Panther  2018
6   Black Panther  2018
7   Black Panther  2018
8   Black Panther  2018
9   Black Panther  2018
10  Black Panther  2018
11  Black Panther  2018
12  Black Panther  2018
13  Black Panther  2018
14  Black Panther  2018
15  Black Panther  2018
16  Black Panther  2018
17  Black Panther  2018
18  Black Panther  2018
19  Black Panther  2018
20  Black Panther  2018
21  Black Panther  2018
22  Black Panther  2018
23  Black Panther  2018
24  Black Panther  2018
25  Black Panther  2018
26  Black Panther  2018
27  Black Panther  2018
28  Black Panther  2018
29  Black Panther  2018
30  Black Panther  2018
31  Black Panther  2018
32  Black Panther  2018
33  Black Panther  2018
34  Black Panther  2018
35  Black Panther  2018
36  Black Panther  2018
37  Black Panther  2018
38  Black Panther  2018
39  Black Panther  2018
40  Black Panther  2018
41  Black Panther  2018
42  Black Panther  2018
43  Black Panther  2018
44  Black Panther  2018
45  Black Panther  2018
46  Black Panther  2018
47  Black Panther  2018
48  Black Panther  2018
49  Black Panther  2018

# 406

In [138]:
# Write a Program for Web scraping using BeautifulSoup to scrape the given data from the given HTML file named
# ‘Popular_Quotes.html’. In the given HTML file, you’ll find 30 Quotes. Scrape the Quote, Author and no of Likes of that particular
# Quote and make a DataFrame of the same

In [139]:
from bs4 import BeautifulSoup
import pandas as pd

file=open("Popular_Quotes.html",encoding="utf-8")
response=file.read()
soup=BeautifulSoup(response,"html.parser")
# soup=soup.prettify()
# print(soup)

In [148]:
quotes=[]
author=[]
likes=[]

a=soup.find("div",class_="mainContentFloat").find_all("div",class_="quoteDetails")

for i in a:
    quotes.append(i.find("div",class_="quoteText").text.strip())
    author.append(i.find("span").text.strip())
    likes.append(i.find("div",class_="right").find("a").text.strip())

import pandas as pd

df=pd.DataFrame({"Quotes ":quotes , "Author ":author , "Likes ":likes})
df

,Quotes,Author,Likes
0,“Be yourself; everyone else is already taken.”...,Oscar Wilde,172090 likes
1,"“I'm selfish, impatient and a little insecure....",Marilyn Monroe,162993 likes
2,"“So many books, so little time.”\n \n ―\n ...",Frank Zappa,147069 likes
3,“Two things are infinite: the universe and hum...,Albert Einstein,146082 likes
4,“A room without books is like a body without a...,Marcus Tullius Cicero,133363 likes
5,"“Be who you are and say what you feel, because...",Bernard M. Baruch,128599 likes
6,“You've gotta dance like there's nobody watchi...,William W. Purkey,127116 likes
7,“You know you're in love when you can't fall a...,Dr. Seuss,124987 likes
8,"“You only live once, but if you do it right, o...",Mae West,117240 likes
9,“Be the change that you wish to see in the wor...,Mahatma Gandhi,113213 likes
10,“In three words I can sum up everything I've l...,Robert Frost,108002 likes
11,"“If you want to know what a man's like, take a...","J.K. Rowling,",100983 likes
12,“Don’t walk in front of me… I may not followDo...,Albert Camus,92274 likes
13,"“If you tell the truth, you don't have to reme...",Mark Twain,90869 likes
14,“Friendship ... is born at the moment when one...,"C.S. Lewis,",87553 likes
15,“I've learned that people will forget what you...,Maya Angelou,87398 likes
16,“A friend is someone who knows all about you a...,Elbert Hubbard,83514 likes
17,“To live is the rarest thing in the world. Mos...,Oscar Wilde,83168 likes
18,“Always forgive your enemies; nothing annoys t...,Oscar Wilde,80923 likes
19,“Darkness cannot drive out darkness: only ligh...,"Martin Luther King Jr.,",77451 likes
20,“Live as if you were to die tomorrow. Learn as...,Mahatma Gandhi,77061 likes
21,“We accept the love we think we deserve.”\n ...,"Stephen Chbosky,",74875 likes
22,"“Without music, life would be a mistake.”\n ...","Friedrich Nietzsche,",73251 likes
23,“I am so clever that sometimes I don't underst...,"Oscar Wilde,",71126 likes
24,“To be yourself in a world that is constantly ...,Ralph Waldo Emerson,69009 likes
25,“Here's to the crazy ones. The misfits. The re...,Steve Jobs,67728 likes
26,"“Insanity is doing the same thing, over and ov...",Narcotics Anonymous,64173 likes
27,“I believe that everything happens for a reaso...,Marilyn Monroe,61795 likes
28,“It is better to be hated for what you are tha...,"Andre Gide,",61028 likes
29,“Twenty years from now you will be more disapp...,"H. Jackson Brown Jr.,",59792 likes

# 407

In [166]:
# 1.Extract the text from the <h1> tag and display it.
# 2.Retrieve the text of the <Ɵtle> tag, then display it in reverse order.
# 3.What is the total number of <script> tags in the HTML?
# 4.Extract all tags listed under the first quote by Oscar Wilde and print the tag with the most characters.
# 5.Print the first 5 quotes along with their authors in the below given format:
# Example:
# Quote: “Be yourself; everyone else is already taken.”
# Author: Oscar Wilde
# 6.Display the quotes that contain the word "accomplishment" in its text.
# 7.Extract the number of likes for each quote and display them in ascending order.
# 8.Find and print the names of authors who have more than one quote on the page.
# 9.Create a DataFrame containing the quote, author name, and number of likes.

In [181]:
p_div = soup.find_all("div", {"class": "quoteDetails"})
quotes = []
authors = []
likes = []

for i in p_div:
    q = i.find("div", {"class": "quoteText"})
    if q:
        quotes.append(q.get_text().strip().split("―")[0].strip())

    a = i.find("span", {"class": "authorOrTitle"})
    if a:
        authors.append(a.get_text().strip())
    l = i.find("a", {"class": "smallText"})
    if l:
        likes.append(int(l.get_text().strip().split(" ")[0]))

df = pd.DataFrame({"Quotes": quotes, "Authors": authors, "Likes": likes})
df

# PB 407
h1 = soup.find_all("h1")
h1_text = []

for i in h1:
    h1_text.append(i.get_text().strip())

h1_text

t = soup.find_all("title")
t_text = []

for i in t:
    t_text.append(i.get_text().strip()[::-1])

t_text

s = soup.find_all("script")
len(s)

tags = []
for i in p_div:
    a = i.find("span", {"class": "authorOrTitle"}).get_text().strip()
    if a == "Oscar Wilde":
        tags_div = i.find("div", {"class": "greyText smallText left"})
        tags_a = tags_div.find_all("a")

        for j in tags_a:
            tags.append(j.get_text().strip())

        break
tags

max_length = 0
max_tag = ""
for i in tags:
    if len(i) > max_length:
        max_length = len(i)
        max_tag = i
max_tag

for i in range(5):
    print(f"Quote: {quotes[i]}")
    print(f"Author: {authors[i]}")
    print()

for i in quotes:
    if "accomplishment" in i:
        print(i)

sorted(likes)

dic = dict()

for i in p_div:
    a = i.find("span", {"class": "authorOrTitle"}).get_text().strip()
    if a in dic:
        dic[a] = dic[a] + 1
    else:
        dic[a] = 1

for i in dic:
    if dic[i] == max(dic.values()):
        print(i)

Quote: “Be yourself; everyone else is already taken.”
Author: Oscar Wilde

Quote: “I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best.”
Author: Marilyn Monroe

Quote: “So many books, so little time.”
Author: Frank Zappa

Quote: “Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.”
Author: Albert Einstein

Quote: “A room without books is like a body without a soul.”
Author: Marcus Tullius Cicero

“To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.”
Oscar Wilde

In [1]:
from bs4 import BeautifulSoup
import pandas as pd

file=open("web_scraping.html",encoding="utf-8")
response=file.read()
soup=BeautifulSoup(response,"html.parser")
# soup=soup.prettify()

In [29]:

table = soup.find("table")
# print(table.prettify())

cols = table.find_all("th")
columns = []

for i in cols:
    col = i.get_text().strip()
    columns.append(col)

print(columns)

body = table.find("tbody")

trs = body.find_all("tr")

all_data = []

for i in range(len(trs)):
    tds = trs[i].find_all("td")

    li = []

    for j in range(len(tds)):
        txt = tds[j].get_text().strip()
        li.append(txt)
    all_data.append(li)


df = pd.DataFrame(all_data , columns = columns)
df

['Transaction ID', 'Product Details', 'Market Region', 'Revenue', 'Platform Fee', 'Purchase Date', 'Delivery Status']

,Transaction ID,Product Details,Market Region,Revenue,Platform Fee,Purchase Date,Delivery Status
0,TXN-90210,"UltraView 32"" Curved Monitor",North America,$449.99,8.5%,2026-01-15,Delivered
1,TXN-90211,SoundPulse Noise-Cancelling Headphones,Europe,$129.50,10.0%,2026-01-18,Shipped
2,TXN-90212,AeroGlide Wireless Mouse,Asia-Pacific,$39.99,5.0%,2026-02-02,Delivered
3,TXN-90213,Titanium mechanical Keyboard,North America,$189.00,8.5%,2026-02-14,Cancelled
4,TXN-90214,Quantum 1TB NVMe SSD,LATAM,$89.95,12.0%,2026-03-01,Delivered
5,TXN-90215,OmniStand Ergonomic Laptop Riser,Europe,$54.20,10.0%,2026-03-12,Shipped
6,TXN-90216,StreamCam 4K Pro Webcam,Asia-Pacific,$199.99,5.0%,2026-04-05,Delivered